---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  gather_facts: true
  become: true
  become_method: sudo
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} - {{ ansible_distribution_version }}"
